AarhusWebDevCoop/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoop.ViewModels
{
    public class ContactForm
    {
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter email address")]
        [Display(Name = "Email")]
        [RegularExpression(@"^([a-zA-z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$", ErrorMessage = "Please enter correct email address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter a subject")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Please enter a message")]
        public string Message { get; set; }
    }
}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using AarhusWebDevCoop.ViewModels;
using System.Net.Mail;
using Umbraco.Core.Models;


namespace AarhusWebDevCoop.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        /// <summary>
        /// Metode der returnerer PartialView Contactform
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //returnerer partielview contatcform
            return PartialView("ContactForm", new ContactForm());
        }

        /// <summary>
        /// Metode der bliver kørt når der trykkes på submit knappen på kontakt formen metoden bliver
        /// defineret i partialview filen
        /// </summary>
        /// <param name="model">objekt af typen ContactForm med indholdet fra felterne i formen</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            //hvis alle required felter ikke er sat returneres til nuværende side
            if (!ModelState.IsValid) { return CurrentUmbracoPage(); }

            //her oprettes et mailmessage object
            MailMessage message = new MailMessage();
            //modtager at beskeden bliver sat
            message.To.Add("npbhdk@gmail.com");
            //subject af beskeden bliver sat fra model objektet
            message.Subject = model.Subject;
            //afsender af beskeden bliver sat fra model objektet
            message.From = new MailAddress(model.Email, model.Name);
            //body bliver sat på beskeden fra model objektet
            message.Body = model.Message;


            //opretter smtp client og sender mail beskeden
            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("npbhdk@gmail.com", "jfajxhzcmffgnbtz");

                // send mail
                smtp.Send(message);
                //sætter tempdata variblen success til true
                TempData["success"] = true;
            }

            //opretter en en besked ved at bruger contentservice api'en og sætter værdierne fra contact form model objektet
            IContent msg = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "message");
            msg.SetValue("messageName", model.Name);
            msg.SetValue("email", model.Email);
            msg.SetValue("subject", model.Subject);
            msg.SetValue("messageContent", model.Message);

            //gemmer beskeden
            Services.ContentService.Save(msg);

            //redirecter til nuværende umbraco side, da TempData["success"] er sat til true bliver formen ikke vist, der bliver 
            //istedet vist en besked om at beskeden er blevet sendt.
            return RedirectToCurrentUmbracoPage();
        }
    }
}

AarhusWebDevCoop/Views/ArticleItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ArticleItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<h1>@Model.ArticleTitle</h1>
<p>@Model.ArticleContent</p>

AarhusWebDevCoop/Views/ArticlesOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ArticlesOverview>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<p>@Model.ArticlesBodyText</p>

@Umbraco.RenderMacro("GetChildren")

AarhusWebDevCoop/Views/ContactUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<p>
    @Html.Action("Index", "ContactFormSurface")
</p>

AarhusWebDevCoop/Views/GridPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.GridPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<p>
@Html.GetGridHtml(@Model, "mitGrid", "Bootstrap3-Fluid")
</p>

AarhusWebDevCoop/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}

<p>
@Model.MainContent
</p>

@Umbraco.RenderMacro("listNewestProjects", new { numOfProjects = "3" })

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@Html.Partial("loginform")

AarhusWebDevCoop/Views/MacroPartials/DropDownMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{
    var selection =
        Model.Content.Site().Children
        .Where(x => x.DocumentTypeAlias == "projectsOverview")
        .First()
        .Children
        .Where(x => x.IsVisible())
        .OrderByDescending(x => x.CreateDate)
        .ToArray();
}

@if (selection.Length > 0)
{
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Projects
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

            @foreach (var item in selection)
            {
                var isProtected = umbraco.library.IsProtected(item.Id, item.Path);
                var loginAccess = isProtected && umbraco.library.HasAccess(item.Id, item.Path);
            
                if(!isProtected|| loginAccess) {
                <a class="dropdown-item" href="@item.Url">@item.Name</a>
                }
            }
        </div>
    </li>
}

AarhusWebDevCoop/Views/MacroPartials/GetChildren.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    This snippet makes a list of links to the of children of the current page using an unordered HTML list.

    How it works:
    - It uses the Children method to get all child pages
    - It then generates links so the visitor can go to each page
*@

@{ var selection = Model.Content.Children.Where(x => x.IsVisible()).OrderByDescending(x => x.CreateDate).ToArray(); }

@if (selection.Length > 0)
{
    <ul>
        @foreach (var item in selection)
        {
            <li>
                <a href="@item.Url">@item.Name</a>
            </li>
        }
    </ul>
}

AarhusWebDevCoop/Views/MacroPartials/GetProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
    var selection =
        Model.Content.Site().Children
        .Where(x => x.DocumentTypeAlias == "projectsOverview")
        .First()
        .Children
        .Where(x => x.IsVisible())
        .OrderByDescending(x => x.CreateDate)
        .ToArray();
}

@if (selection.Length > 0)
{

            foreach (var item in selection)
            {
                var isProtected = umbraco.library.IsProtected(item.Id, item.Path);
                var loginAccess = isProtected && umbraco.library.HasAccess(item.Id, item.Path);
            
                if(!isProtected|| loginAccess) {
                    <li>
                        <a href="@item.Url">@item.Name</a>
                    </li>
                }
            }

}

AarhusWebDevCoop/Views/MacroPartials/Show Images.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@*
    Macro to display a series of images from a media folder.

    How it works:
        - Confirm the macro parameter has been passed in with a value
        - Loop through all the media Ids passed in (might be a single item, might be many)
        - Display any individual images, as well as any folders of images

    Macro Parameters To Create, for this macro to work:
    Alias:mediaId     Name:Select folder with images    Type:Single Media Picker
*@

@{ var mediaId = Model.MacroParameters["mediaId"]; int id; }
@if (mediaId != null)
{
    @* Get the media item associated with the id passed in *@
    var media = Umbraco.TypedMedia(mediaId);
    if (media != null)
    {
    var selection = media.Children<Image>().ToArray();

    if (selection.Length > 0)
    {
        <div class="imagebox">
            @foreach (var item in selection)
            {
                <div>
                    <a href="@item.Url" data-lightbox="test">
                    <img src="@item.Url" alt="@item.Name" width="150" />
                    </a>
                </div>
            }
        </div>
    }
    }
}

AarhusWebDevCoop/Views/MacroPartials/listNewestProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@{ 
int numOfProjects = Convert.ToUInt16(Model.MacroParameters["numOfProjects"]);
var selection = 
    Model.Content.Children
    .Where(x => x.DocumentTypeAlias == "projectsOverview")
    .First()
    .Children
    .Where(x => x.HasValue("projectStatus") && Umbraco.GetPreValueAsString(x.GetPropertyValue<int>("projectStatus")) == "Completed")
    .OrderByDescending(x => x.CreateDate)
    .Take(numOfProjects)
    .ToArray(); 
}

@if (selection.Length > 0)
{
    <ul>
        @foreach (var item in selection)
        {
            <li><a href="@item.Url">@item.Name</a></li>
        }
    </ul>
}

AarhusWebDevCoop/Views/MacroPartials/mainMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web

@{
    //Opretter reference til roden af websitet
    var root = Model.Content.Site();
    //henter alle underelementer fra roden der er synlige ie. ikke har slået umbracoNaviHide til 
    var selection = root.Children.Where(x => x.IsVisible()).ToArray();
}

@* laver et check om der er nogle synlige elementer *@
@if (selection.Length > 0)
{
    @* tilføjer rod elementet til menuen og tilføj active klassen hvis rod elementet er nuværende side *@
    <li class="nav-item @(Model.Content.Level == 1 ? "active" : null)">
    @* laver et html link  med klassen nav-link et href med  url fra root elementer og navnet på root elementet *@
        <a class="nav-link" href="@root.Url">@root.Name</a>
    </li>
    
    @* looper alle fundne elementer igennem *@
    foreach (var item in selection)
    {
        @* henter protected info om item elementet  *@
        var isProtected = umbraco.library.IsProtected(item.Id, item.Path);
        
        @* kigger om der er adgang til elementet *@
        var loginAccess = isProtected && umbraco.library.HasAccess(item.Id, item.Path);
    
        @* hvis elementet ikke er protected eller der er adgang til elementet køres indholdet af if sætningen *@
        if(!isProtected|| loginAccess) {
        @* opretter li element med klassen nav-item og klassen active hvis nuværende side er elementet selv eller har elementet som parent *@
        <li class="nav-item @(item.IsAncestorOrSelf(Model.Content) ? "active" : null)">
            @*hvis elementets navn er login og man er logget ind på siden skrives Profil istedet for Login i menuen*@
            @if(item.Name == "Login" && Members.GetCurrentLoginStatus().IsLoggedIn)
            {
                <a class="nav-link" href="@item.Url">Profil</a>
            }
            @*hvis elementets navn er Projects køres dropdown menu macroen der udskriver project drop down menuen*@
            else if(item.Name == "Projects")
            {
                @Umbraco.RenderMacro("DropDownMenu");
            }
            @*ellers udskrives menu punktet normalt*@
            else
            {
                <a class="nav-link" href="@item.Url">@item.Name</a>
            }
        </li>
        }
    }
}

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.Master>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = null;
}

<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>@Umbraco.Field("siteTitle", recursive: true)</title>
    <meta name="description" content="@Model.MetaDescription">
    <meta name="keywords" content="@Model.MetaKeywords">
    <meta name="author" content="Niels Bang-Hansen">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <link rel="stylesheet" href="/css/Default.css" />
    <link rel="stylesheet" href="/css/lightbox.css">
    <script src="~/Scripts/lightbox-plus-jquery.min.js"></script>
    
</head>
<body>
    <div id="header-container">
        <header class="wrapper clearfix">
            <div class="col-md-11" style="width: 80em; margin: auto;">
            <h1 id="title">@Umbraco.Field("siteTitle", recursive: true)</h1>
            </div>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="nav navbar-nav">
                        @Umbraco.RenderMacro("mainMenu")
                    </ul>
                </div>
            </nav>
        </header>
    </div>
    <div class="col-md-11" style="width: 80em; margin: auto; min-height: 20em">
    @RenderBody()
    </div>
    <footer class="page-footer font-small bg-dark footer-copyright text-center text-light py-1">
            @Umbraco.Field("footer", recursive: true)
    </footer>
</body>
</html>

AarhusWebDevCoop/Views/MemberList.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MemberList>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Newtonsoft.Json;
@using Umbraco.Web.Models;
@{
	Layout = "Master.cshtml";
	var memberService = ApplicationContext.Current.Services.MemberService;
    var members = memberService.GetMembersByGroup("Active");
    var membersGuest = memberService.GetMembersByGroup("Guest");
}

<div>
<table style="margin: auto">
    <tr valign="top">
        <td>
            <h2>Active Members</h2>
                @foreach(var member in members) 
                {
                    <p>@member.Name
                    <br>@member.GetValue("address")
                    <br>@member.GetValue("zip") @member.GetValue("city") 
                    <br>Email: @member.Email
                    <br>Skills: 
                        @if (member.GetValue("skills") != null)
                        {
                            string[] skills = member.GetValue("skills").ToString().Split(',');
                            
                            string skillString = 
                            string.Join(", ", from skill in skills 
                            select umbraco.library.GetPreValueAsString(Convert.ToInt32(skill)));
                            
                            <span>@skillString</span>
                        }
                        
                        <br/>Photo:
                        @if(member.GetValue("photo") != null) 
                        {
                            string image = member.GetValue<string>("photo");
                            if(image != null) 
                            {
                                ImageCropDataSet imageCrop = JsonConvert.DeserializeObject<ImageCropDataSet>(image);
                                <img style="border-radius: 50%" src="@imageCrop.Src.GetCropUrl(width: 100)"/>
                            }
                        }
                        
                        
                    </p>
                }
        </td>
        <td>
            <h2>Guest Members</h2>
                @foreach(var member in membersGuest) 
                {
                    <p>@member.Name
                    <br>Email: @member.Email
                    </p>
                }
        </td>
    </tr>
    </table>
</div>
</center>

AarhusWebDevCoop/Views/Partials/ContactForm.cshtml
@model AarhusWebDevCoop.ViewModels.ContactForm
@{
 Layout = null;
}

@if (TempData["success"] == null)
{
 using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { }, new { @class = "form-horizontal" }))
{

<div class="form-group">
    @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-6">
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-6">
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
        @Html.ValidationMessageFor(m => m.Email)
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-6">
        @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
        @Html.ValidationMessageFor(m => m.Subject)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
    <div class="col-sm-6">
        @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
        @Html.ValidationMessageFor(m => m.Message)
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
        <button id="contact-submit" type="submit" class="btn btn-primary input-medium pullleft">Send</button>
    </div>
</div>
 }
}
else
{
<p>Thank you for contacting us. We’ll be in touch soon!</p>
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

AarhusWebDevCoop/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

AarhusWebDevCoop/Views/ProjectsOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContentModels.ProjectsOverview>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<p>@Model.ProjectsBodyText</p>

@Umbraco.RenderMacro("GetProjects")